-- ************************* SqlDBM: PostgreSQL *************************
-- **** Generated by SqlDBM: kds_discovery by keeshinds.com 20240903  ***


CREATE SCHEMA load;

-- ************************************** load.subsidiary
CREATE TABLE load.subsidiary
(
 parent_           varchar(96) NOT NULL,
 name_             varchar(96) NOT NULL,
 organization_type varchar(32) NULL,
 ticker_           varchar(8) NULL,
 nasic_code        varchar(8) NULL,
 product_service   varchar(72) NULL,
 annual_revenue    numeric(15, 2) NULL,
 employee_total    int NULL,
 website_          varchar(92) NULL,
 location_         varchar(48) NULL,
 source_           varchar(48) NOT NULL,
 create_date       date NOT NULL,
 created_by        varchar(92) NOT NULL,
 modified_date     date NULL,
 modified_by       varchar(92) NULL

);


-- ************************************** load.parent
CREATE TABLE load.parent
(
 name_             varchar(96) NOT NULL,
 organization_type varchar(32) NULL,
 ticker_           varchar(8) NULL,
 nasic_code        varchar(8) NULL,
 product_service   varchar(128) NULL,
 annual_revenue    numeric(15, 2) NULL,
 employee_total    int NULL,
 website_          varchar(92) NULL,
 location_         varchar(48) NULL,
 source_           varchar(48) NOT NULL,
 create_date       date NOT NULL,
 created_by        varchar(92) NOT NULL,
 modified_date     date NULL,
 modified_by       varchar(92) NULL

);


-- ************************************** load.model_question
CREATE TABLE load.model_question
(
 nasic_code         varchar(8) NOT NULL,
 business_unit      varchar(96) NOT NULL,
 role_              varchar(96) NOT NULL,
 model_topic        varchar(96) NOT NULL,
 topic_             varchar(96) NOT NULL,
 subtopic_          varchar(96) NULL,
 syntax_            varchar(1024) NOT NULL,
 help_              varchar(1024) NULL,
 type_              varchar(32) NOT NULL,
 sort_order         smallint NOT NULL,
 location_reference varchar(96) NULL,
 create_date        date NOT NULL,
 modified_date      date NULL,
 source_            varchar(96) NULL

);


-- ************************************** load.model
CREATE TABLE load.model
(
 nasic_code    varchar(8) NOT NULL,
 biz_unit      varchar(96) NOT NULL,
 role_         varchar(96) NOT NULL,
 create_date   date NULL,
 created_by    varchar(92) NOT NULL,
 modified_date date NULL,
 modified_by   varchar(72) NULL,
 source_       varchar(72) NOT NULL

);


-- ************************************** load.industry
CREATE TABLE load.industry
(
 nasic_code   varchar(8) NOT NULL,
 description_ varchar(128) NOT NULL

);


-- ************************************** load.contact
CREATE TABLE load.contact
(
 email_          varchar(128) NOT NULL,
 parent_         varchar(96) NOT NULL,
 subsidiary_     varchar(96) NULL,
 business_unit   varchar(96) NOT NULL,
 nasic_code      varchar(8) NOT NULL,
 title_          varchar(64) NULL,
 role_           varchar(50) NOT NULL,
 respondent_     varchar(12) NOT NULL,
 project_sponsor varchar(12) NOT NULL,
 first_name      varchar(32) NULL,
 last_name       varchar(92) NOT NULL,
 location_       varchar(48) NULL,
 phone_          varchar(16) NULL,
 create_date     date NOT NULL,
 created_by      varchar(92) NOT NULL,
 modified_date   date NULL,
 modified_by     varchar(92) NULL

);


-- ************************************** load.business_unit
CREATE TABLE load.business_unit
(
 name_           varchar(96) NOT NULL,
 parent_         varchar(96) NOT NULL,
 subsidiary_     varchar(96) NULL,
 nasic_code      varchar(8) NOT NULL,
 model_reference varchar(255) NOT NULL,
 create_date     date NOT NULL,
 created_by      varchar(92) NOT NULL,
 modified_date   date NULL,
 modified_by     varchar(72) NULL,
 source_         varchar(72) NOT NULL

);


