-- ************************* SqlDBM: PostgreSQL *************************
-- **** Generated by SqlDBM: kds_discovery by keeshinds.com 20240903***


CREATE SCHEMA stage;

-- ************************************** stage.subsidiary
CREATE TABLE stage.subsidiary
(
 name_             varchar(96) NOT NULL,
 parent_name       varchar(96) NOT NULL,
 organization_type varchar(32) NULL,
 ticker_           varchar(8) NULL,
 nasic_code        varchar(8) NULL,
 product_service   varchar(32) NULL,
 annual_revenue    numeric(15, 2) NULL,
 employee_total    int NULL,
 website_          varchar(92) NULL,
 location_         varchar(48) NULL,
 source_           varchar(48) NOT NULL,
 create_date       date NOT NULL,
 created_by        varchar(92) NOT NULL,
 modified_date     date NULL,
 modified_by       varchar(92) NULL,
 hash_key          varchar(32) NULL,
 CONSTRAINT PK_stage_sub PRIMARY KEY ( name_, parent_name )
);


-- ************************************** stage.parent
CREATE TABLE stage.parent
(
 name_             character varying(96) NOT NULL,
 organization_type character varying(32) NULL,
 ticker_           character varying(8) NULL,
 nasic_code        character varying(8) NOT NULL,
 product_service   character varying(128) NULL,
 annual_revenue    numeric(15,2) NULL,
 employee_total    integer NULL,
 website_          character varying(92) NULL,
 location_         character varying(48) NULL,
 source_           character varying(48) NOT NULL,
 create_date       date NOT NULL,
 created_by        character varying(92) NOT NULL,
 modified_date     date NULL,
 modified_by       character varying(92) NULL,
 parent_id         uuid NULL,
 CONSTRAINT pk_stage_parent PRIMARY KEY ( name_, nasic_code )
);


-- ************************************** stage.model_question
CREATE TABLE stage.model_question
(
 question_id        uuid NOT NULL DEFAULT gen_random_uuid(),
 nasic_code         varchar(8) NOT NULL,
 business_unit      varchar(96) NOT NULL,
 role_              varchar(96) NOT NULL,
 model_topic        varchar(96) NOT NULL,
 topic_             varchar(96) NOT NULL,
 subtopic_          varchar(96) NULL,
 syntax_            jsonb NOT NULL,
 help_              jsonb NULL,
 type_              varchar(32) NOT NULL,
 sort_order         smallint NOT NULL,
 location_reference varchar(96) NULL,
 create_date        date NOT NULL,
 modified_date      date NULL,
 source_            varchar(92) NULL,
 CONSTRAINT PK_34 PRIMARY KEY ( question_id )
);


-- ************************************** stage.model
CREATE TABLE stage.model
(
 nasic_code    varchar(8) NOT NULL,
 biz_unit      varchar(96) NOT NULL,
 role_         varchar(96) NOT NULL,
 create_date   date NULL,
 created_by    varchar(92) NOT NULL,
 modified_date date NULL,
 modified_by   varchar(72) NULL,
 source_       varchar(72) NOT NULL,
 hash_key      varchar(32) NULL,
 CONSTRAINT PK_stage_model PRIMARY KEY ( nasic_code, biz_unit, role_ )
);


-- ************************************** stage.industry
CREATE TABLE stage.industry
(
 nasic_code   varchar(8) NOT NULL,
 description_ varchar(128) NOT NULL,
 CONSTRAINT PK_stage_nasic PRIMARY KEY ( nasic_code )
);


-- ************************************** stage.contact
CREATE TABLE stage.contact
(
 email_             varchar(128) NOT NULL,
 parent_            varchar(96) NOT NULL DEFAULT gen_random_uuid(),
 subsidiary_        varchar(96) NOT NULL,
 business_unit      varchar(96) NOT NULL,
 title_             varchar(64) NULL,
 role_              varchar(50) NOT NULL,
 respondent_        varchar(12) NULL,
 project_sponsor    varchar(12) NOT NULL,
 first_name         varchar(48) NULL,
 last_name          varchar(32) NULL,
 location_reference varchar(96) NULL,
 phone_             varchar(16) NULL,
 create_date        date NOT NULL,
 created_by         varchar(92) NOT NULL,
 modified_date      date NULL,
 modified_by        varchar(92) NULL,
 hash_key           varchar(32) NULL,
 CONSTRAINT PK_client_contact PRIMARY KEY ( email_, parent_, subsidiary_, business_unit )
);


-- ************************************** stage.business_unit
CREATE TABLE stage.business_unit
(
 name_         varchar(96) NOT NULL,
 parent_       varchar(96) NOT NULL,
 subsidiary_   varchar(96) NOT NULL,
 create_date   date NOT NULL,
 created_by    varchar(92) NOT NULL,
 modified_date date NULL,
 modified_by   varchar(72) NULL,
 source_       varchar(72) NOT NULL,
 hash_key      varchar(32) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( name_, parent_, subsidiary_ )
);


